export const NAVIGATE_SOURCES = 'NAVIGATE_SOURCES';
export const NAVIGATE_ARTICLES = 'NAVIGATE_ARTICLES';
export const ROUTE_NOT_FOUND = 'ROUTE_NOT_FOUND';
export const ROUTE_CHANGED = 'ROUTE_CHANGED';  